"""Fix mixtape item relationships

Revision ID: aa6ec36148a9
Revises: d7a6d4245c16
Create Date: 2025-02-13 01:16:35.715203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa6ec36148a9'
down_revision = 'd7a6d4245c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixtape_items', schema=None) as batch_op:
        batch_op.alter_column('mixtape_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mixtape_items', schema=None) as batch_op:
        batch_op.alter_column('song_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mixtape_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
